# Generated by Django 4.1 on 2023-12-02 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotable",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todotable",
            name="priority",
            field=models.CharField(
                choices=[("danger", "high"), ("info", "normal"), ("success", "low")],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
