# Generated by Django 4.1 on 2023-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0002_todotable_deadline_todotable_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotable",
            name="priority",
            field=models.CharField(
                choices=[("High", "high"), ("Normal", "normal"), ("Low", "low")],
                max_length=50,
            ),
        ),
    ]
